[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "node bootstrap/ssr/ssr.js & php artisan serve --host=0.0.0.0 --port=$PORT"
